apiVersion: apps/v1
kind: Deployment
metadata:
  name: symfony-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: symfony
  template:
    metadata:
      labels:
        app: symfony
    spec:
      containers:
      - name: symfony
        image: symfony-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
