apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.2.1-apache
        env:
         - name: WORDPRESS_DB_HOST
           value: "10.104.177.52"
         #- name: WORDPRESS_DB_NAME
         #  value: wordpress
         - name: WORDPRESS_DB_USER
           value: "wordpress"
         - name: WORDPRESS_DB_PASSWORD
           value: "wordpress"
         - name: WORDPRESS_DEBUG
           value: "1"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc
